"""Exercise execution engines through the running tools API and real chat loop.

Fixtures are supplied by this audit, not generated by the neural model. Passing
does not demonstrate general coding competence or neural generalization.
"""
import argparse
import json
from pathlib import Path
import tempfile
import time
import urllib.request
from uuid import uuid4


def request(base, path, body):
    req=urllib.request.Request(base+path,data=json.dumps(body).encode(),
                              headers={'Content-Type':'application/json'})
    with urllib.request.urlopen(req,timeout=90) as response:return json.load(response)


def audit(base):
    rows=[]
    def tool(name,args):return request(base,'/api/v1/tools/call',{'tool':name,'arguments':args})
    def record(name,action,check):
        started=time.monotonic()
        try:
            observed=action();passed=bool(check(observed))
            row={'case':name,'passed':passed,'observed':observed}
        except Exception as error:row={'case':name,'passed':False,'error':str(error)}
        row['seconds']=round(time.monotonic()-started,3);rows.append(row)
        print(('PASS' if row['passed'] else 'FAIL')+' '+name,flush=True)
    def result_is(expected):
        return lambda row: row.get('ok') is True and row.get('data',{}).get('passed') is True \
            and row['data'].get('result')==expected
    def rejected(error):
        return lambda row: row.get('ok') is True and row.get('data',{}).get('passed') is False \
            and row['data'].get('error',{}).get('type')==error
    def chat(prompt,workspace=None):
        payload={'schema':'agent-request/v2','objective':'auto','prompt':prompt,
                 'operation_id':'agent-core-engine-audit-'+uuid4().hex}
        if workspace:payload['workspace_root']=str(workspace)
        return request(base,'/api/v1/agent/pursue',payload)
    def answered(fragment):
        return lambda row: row.get('report',{}).get('status')=='completed' \
            and fragment in str(row['report'].get('finalText'))
    def blocked(fragment):
        return lambda row: row.get('report',{}).get('status')=='blocked' \
            and fragment.lower() in str(row['report'].get('finalText')).lower()
    def one_function_call(row):
        return sum(event.get('phase')=='act' and event.get('kind')=='brain.state'
            and event.get('payload',{}).get('tool')=='evaluate_function'
            for event in row.get('report',{}).get('events',[]))==1

    original=tool('inspect_project',{}).get('data',{}).get('workspace')
    with tempfile.TemporaryDirectory(prefix='ia-execution-engine-audit-') as temporary:
        root=Path(temporary);marker=root/'top-level-marker'
        source=f'''from pathlib import Path
Path({str(marker)!r}).write_text('must not run')
def merge_segments(rows):
    merged=[]
    for start,end in sorted(rows):
        if merged and start<=merged[-1][1]:merged[-1][1]=max(merged[-1][1],end)
        else:merged.append([start,end])
    return merged
def weighted(rows,bonus=0):
    return sum(pair[0]*pair[1] for pair in rows)+bonus
def restricted():
    import os
    return os.getcwd()
def spin():
    while True:pass
'''
        (root/'logic.py').write_text(source)
        try:
            selected=tool('set_workspace',{'path':str(root)})
            if selected.get('ok') is not True:raise RuntimeError('Disposable workspace not selected')
            record('runtime-catalog',lambda:tool('list_tools',{}),lambda row:
                {'calculate','evaluate_function'} <= {item['name'] for item in row.get('data',{}).get('tools',[])})
            record('expression-with-new-variables',lambda:tool('calculate',{
                'expression':'(income-cost)/len(items)','variables':{'income':1937,'cost':221,'items':[1,2,3,4]}}),result_is(429))
            record('generator-short-circuit',lambda:tool('calculate',{
                'expression':'any(x==1 or 1/0 for x in [1,0])'}),result_is(True))
            record('exact-large-integer',lambda:tool('calculate',{
                'expression':'2**200+17'}),result_is({'integer_decimal':str(2**200+17)}))
            record('source-function-with-new-inputs',lambda:tool('evaluate_function',{
                'path':'logic.py','function':'merge_segments','args':[[[9,12],[-2,3],[2,7],[7,10]]]}),
                lambda row: result_is([[-2,12]])(row) and row['data'].get('top_level_executed') is False
                    and len(row['data'].get('source_sha256',''))==64 and not marker.exists())
            record('helper-arguments-and-keywords',lambda:tool('evaluate_function',{
                'path':'logic.py','function':'weighted','args':[[[3,9],[4,7],[8,2]]],'kwargs':{'bonus':11}}),result_is(82))
            record('new-arguments-change-result',lambda:tool('evaluate_function',{
                'path':'logic.py','function':'weighted','args':[[[2,5],[7,8]]],'kwargs':{'bonus':3}}),result_is(69))
            record('host-access-rejected',lambda:tool('calculate',{
                'expression':"__import__('os').getcwd()"}),rejected('UnsupportedSyntax'))
            record('imports-rejected-with-specific-error',lambda:tool('evaluate_function',{
                'path':'logic.py','function':'restricted'}),rejected('UnsupportedSyntax'))
            record('endless-loop-interrupted',lambda:tool('evaluate_function',{
                'path':'logic.py','function':'spin'}),rejected('LimitExceeded'))
            record('oversized-allocation-rejected',lambda:tool('calculate',{
                'expression':"'x'*1000000000"}),rejected('LimitExceeded'))
            record('chat-computes-composed-expression',lambda:chat('Calcule (1275 * 3 + 18) / 7'),answered('549'))
            record('chat-respects-question-inside-string',lambda:chat("Calcule len('a?b')?"),answered('3'))
            record('chat-initial-demo-composes-generator-and-arithmetic',lambda:chat(
                'Calcule sum(x*x for x in range(17)) + 23'),answered('1519'))
            record('chat-calls-function-engine-and-synthesizes',lambda:chat(
                'Execute merge_segments([[9, 12], [-2, 3], [2, 7], [7, 10]]) em logic.py',root),
                lambda row: answered('[[-2, 12]]')(row) and one_function_call(row))
            record('chat-with-different-function-arguments',lambda:chat(
                'Execute weighted([[2, 5], [7, 8]], bonus=3) em logic.py',root),
                lambda row: answered('69')(row) and one_function_call(row))
            record('chat-does-not-claim-division-by-zero-success',lambda:chat('Calcule 8 / 0'),blocked('division by zero'))
            record('chat-reports-unsupported-source-specifically',lambda:chat('Execute restricted() em logic.py',root),
                lambda row: blocked('Import')(row) and one_function_call(row))
        finally:
            if original:tool('set_workspace',{'path':original})
    return {'schema':'execution-engines-audit/v1','cases':rows,
            'passed':sum(row['passed'] for row in rows),'total':len(rows),
            'fixture_origin':'audit-authored-source-not-neural-generation',
            'general_programming_mastery':False,'general_python_execution':False}


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--base-url',default='http://127.0.0.1:3000')
    parser.add_argument('--output',required=True,type=Path);args=parser.parse_args()
    report=audit(args.base_url);args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
    print(f"{report['passed']}/{report['total']} checks passed",flush=True)
    raise SystemExit(0 if report['passed']==report['total'] else 1)


if __name__=='__main__':main()
